name: Backup gh-pages branch on change (safe)

on:
  push:
    # Only back up when main changes. Do NOT trigger on gh-pages to avoid loops.
    branches:
      - main

jobs:
  backup:
    # Skip this job when the actor is the Actions bot (prevents loop if a workflow pushed)
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create timestamped backup branch
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ts=$(date -u +"%Y%m%dT%H%M%SZ")
          git checkout -B backup-gh-pages-${ts}
          git commit --allow-empty -m "Backup gh-pages snapshot @ $GITHUB_SHA"
          git push --force "https://x-access-token:${TOKEN}@github.com/${REPO}.git" HEAD:backup-gh-pages-${ts}
