name: Backup gh-pages branch on change

on:
  push:
    branches:
      - gh-pages
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create timestamped backup branch
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ts=$(date -u +"%Y%m%dT%H%M%SZ")
          # create a branch named backup-gh-pages-<timestamp> and push it to the repo
          git checkout -B backup-gh-pages-${ts}
          git commit --allow-empty -m "Backup gh-pages snapshot @ $GITHUB_SHA"
          git push --force "https://x-access-token:${TOKEN}@github.com/${REPO}.git" HEAD:backup-gh-pages-${ts}
